### ISSUE TITLE
Investigate using Squoosh Library

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-img#106]
https://twitter.com/DasSurma/status/1408401520677302272

suggested by https://twitter.com/daKmoR

**Comment by surma** [comment]
The CLI is here: https://npm.im/@squoosh/lib
Here is the underlying libSquoosh: https://npm.im/@squoosh/lib

**Comment by jaunt** [comment]
Would integrating https://github.com/imagemin/imagemin be an alternative worth looking at?

**Comment by dawaltconley** [comment]
> Would integrating https://github.com/imagemin/imagemin be an alternative worth looking at?

It looks like the imagemin creator is [recommending squoosh instead.](https://github.com/imagemin/imagemin/issues/385) fwiw I haven't tried squoosh, but in past projects found that imagemin extended build times too much to be worth the often-very-small reduction in file sizes.

**Comment by zachleat** [comment]
Putting this in the enhancement queue.

> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy-img/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by philiprenich** [comment]
A few months (Sept '21) ago I did an evaluation of Tinify, Squoosh, and Sharp for a client. They were initially looking to use the paid Tinify API so I looked at alternatives. Because of their use case this report may not be a direct comparison for 11ty, but I thought maybe it would be useful and save you some time. I'm just going to copy in what I wrote for them, so there may be a couple things you can ignore (like AWS Lambda or Tinify discussion points). Here it is:

---

I have run some tests with Tinify (TinyPNG), Sharp, and Squoosh. The results are below.

Following this I would recommend we use the Sharp package. They have good documentation, including information about AWS Lambda installs (and help Issues). Dependant binaries already exist on popular OSes or can be installed when the Node package installs.

Squoosh is labelled as experimental (though, given it's Google, that can still mean production). Their documentation is light and it is explicitly said they are not trying to be the fastest. However, Squoosh seems to perform slightly better with PNGs (longer processing time, slightly better output), so it could be considered if PNGs are the only file type we will process.

Tinify isn't worth it - the time and money cost to send to a 3rd party API with little to no configuration doesn't make it worthwhile. It also isn't well maintained.

# PNG

Processing 10 images (5 large, 5 small). PNGs are lossless so the only way to reduce filesize is to reduce colours by changing to an index 256 pallette of colours. This is what TinyPNG does. The difference is noticeable.

| Name | Size lg | Size sm | Time | Quality |
|---|---:|---:|---:|---|
| Original | 1.468mb | 46.35kb | N/A | N/A |
| Squoosh | 298kb | 12kb | 11s | Best? | 
| Tinify | 265kb | 11kb | 44s | Worst? |
| Sharp | 374kb | 14kb | 4.1s | Best? |

Visual quality varied dependant on the part of the image examined. Generally this was in the color selected or the dithering style.

# JPEG

Processing 5 images, all same size. Tinify doesn't allow quality variations and is only shown in the Low Quality table.

## Low Quality

| Name | Size | Time | Quality |
|---|---:|---:|---|
| Original | 1.017mb | N/A | N/A |
| Squoosh | 140kb | 3.3s | 85 |
| Tinify | 117kb | 7.9s-29s | N/A |
| Sharp | 125kb | 0.45s | 85 |

Visually, Tinify was the slightest bit worse than Squoosh or Sharp. The latter two were the same.

## High Quality

| Name | Size | Time | Quality |
|---|---:|---:|---|
| Original | 1.017mb | N/A | N/A |
| Squoosh | 892kb | 5.4s | 100 |
| Squoosh (auto) | 423kb | 33s | variable |
| Sharp | 579kb | 1s | 100 |

Visually, these match the quality of the original.

**Comment by daKmoR** [comment]
@philiprenich thank you for this info - nice to see some actual numbers 👍

One potential downside of sharp is that it distributes all its different platform variation binaries via a "curl download" in a npm postinstall...
which means that the machine installing needs to have internet access.
This can be a problem in corporate settings where CI machines might not have internet access at all (only access to a private npm registry) or where users only have internet via a specific proxy that might not be configured for the terminal...

there is a section in the docs for it
https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries

This was the main original motivation to look into squoosh as it's a single wasm file for all platforms (that is part of the npm package)

**Comment by zeroby0** [comment]
The longer processing times, imo, are affordable because we only need to process the images once.

I don't know if this applies to Chrome's projects as well, but Google has a history of abandoning it's projects, even [really](https://github.com/google/python-fire) [popular](https://github.com/google/guetzli) [projects](https://github.com/GoogleChromeLabs/ndb).

So we should have a plan for if/when Squoosh goes unmaintained.

**Comment by zachleat** [comment]
https://www.npmjs.com/package/@squoosh/lib

> Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), this package is no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The [squoosh.app](https://squoosh.app/) web app will continue to be supported and improved.
