### ISSUE TITLE
potential Windows and path.join issue

### ISSUE THREAD

**Issue by jshwlkr** [11ty/eleventy-img#30]
If I use eleventy-img on Windows, the output URLs are composed with backslashes. I believe that is because path.join is cross-platform and will use the OS default (which is a backslash in the case of Windows), so it's not necessarily suitable to construct URLs without some intervention on Windows.

**Comment by Grunet** [comment]
Do you have a minimal example of the HTML where that causes problems? It seems to work ok for me on Windows and in Firefox even though the separators are reversed as you pointed out.

Here's what I ended up with after a while of trying to get eleventy-img to work for my case:

```html
<picture>
  <source type="image/webp" srcset="\img\12f53e2-320.webp 320w, \img\12f53e2-640.webp 640w, \img\12f53e2-960.webp 960w, \img\12f53e2.webp 1056w">
  <source type="image/jpeg" srcset="\img\12f53e2-320.jpeg 320w, \img\12f53e2-640.jpeg 640w, \img\12f53e2-960.jpeg 960w, \img\12f53e2.jpeg 1056w">
  <img src="\img\12f53e2-320.jpeg" alt="Very descriptive alt text" width="320" height="97">
</picture>
```

I also just tried sticking in an absolute URL with back slashes instead of forward slashes into the generated HTML and that image loaded fine as well.

**Comment by g41nxe** [comment]
can confirm its not working on firefox 83.0 on windows using the responsive example from the readme

**Comment by zachleat** [comment]
lol “attempt to fix” closes

**Comment by zachleat** [comment]
Fixed! Test suite added for Windows and passing here: https://github.com/11ty/eleventy-img/actions/runs/458710399

This will roll up with the next version.
