### ISSUE TITLE
Persist in-memory cache

### ISSUE THREAD

**Issue by kamituel** [11ty/eleventy-img#51]
In-memory cache is empty whenever Eleventy build starts from scratch. It's not an issue for sites with small number of images. But for sites with large number of large images, compressing them takes quite a lot of time.

In my case (https://kamituel.pl) I've over 300 high resolution source images that I'd ideally serve in 2-3 formats (avif, jpg, maybe webp) in multiple sizes.

I propose a new config option that would, if enabled, persist the in-memory cache to disk and reuse it the next time the build starts.

If maintainers consider this idea to be a good candidate to exist in eleventy-img itself, I'd be happy to formulate this proposal more concretely and later help / submit a PR.

**Comment by dimitrinicolas** [comment]
For thoses wanting a quick solution for caching optimized images whenever build starts from scratch, here is a solution.

Warning, it checks for already existing file outputs by looking if their output path file is existing, it may or may not be ideal depending on your [`filenameFormat` configuration](https://www.11ty.dev/docs/plugins/image/#custom-filenames-new-in-image-0.4.0).

```js
const fs = require('fs');
const Image = require('@11ty/eleventy-img');
const path = require('path');

/** ... */

const stats = Image.statsSync(src, options);

/** Creating a flat array of all the output paths from the stats object. */
const outputPaths = Object.keys(stats).reduce((acc, key) => {
  return [
    ...acc,
    ...stats[key].map((resource) => {
      return resource.outputPath;
    }),
  ];
}, []);

/** Checking if all output files exists. */
let hasImageBeenOptimized = true;
for (const outputPath of outputPaths) {
  /** Edit the output file path resolving, depending of this file 
  if (!fs.existsSync(path.resolve(__dirname, '..', '..', outputPath))) {
    hasImageBeenOptimized = false;
  }
}

if (!hasImageBeenOptimized) {
  Image(src, options);
}
```

If you are deploying on Netlify you can cache your `eleventy-img` output directory using [`netlify-plugin-cache`](https://github.com/jakejarvis/netlify-plugin-cache).

```bash
npm install netlify-plugin-cache
```

In your `netlify.toml`:

```toml
[[plugins]]
  package = "netlify-plugin-cache"
    [plugins.inputs]
      paths = ["<YOUR OUTPUT DIR PATH>"]
```

**Comment by marcamos** [comment]
I would _love_ for something like this to exist in the official plugin. I thought I was doing something wrong when I saw that builds took three minutes (converting 22 images into three formats and ten sizes each [though, maybe _that's_ overkill?]).

**Comment by snibbo71** [comment]
Just adding my tuppence here, that I'd like this too as I'm using the Image.generateHTML code to pull images remotely. The caching side of it works, but 11ty still chucks those cached images through the resizing process which annoys my laptop and takes a lot longer than is ideal :)

I'm really not clear on how to get Dimitri's work-around to work with the generateHTML method - if indeed I can

**Comment by dimitrinicolas** [comment]
@snibbo71 My piece of code does not take into account whether the resource is remote or local. I use it with the html generation function. After my shortcode, you can generate your html code with the `stats` object returned by `Image.statsSync `, e.g.:

```js
const imageAttributes = {
  // [...]
};

const html = Image.generateHTML(stats, imageAttributes, {
  whitespaceMode: 'inline',
});
```

Both `Image.statsSync` and `Image.generateHTML` are not generating resized/optimized images output files. The `Image.statsSync` is just returning the output file paths that the async `Image.stats` would "normally" export.

Then in my shortcode, we check if those output files are existing (that's why we rely on a hashed src+file size string in output file names), if not, we call the `Image.stats` async function, but we do not have to wait for it to resolves to generate the html. The whole html code generation is async.

**Comment by snibbo71** [comment]
Heya, thanks for the quick reply. I must be doing something entirely wrong because nothing is cached in my setup - even local stuff. Remote images just blow your code up unfortunately :) (Actually, it's the fs.statSync and Image.statSync that dies with ENOENT - which isn't entirely surprising)

I shall keep playing. I have too many images to deal with to have to redo them every time I change a template :) If I come up with anything I'll post back

**Comment by snibbo71** [comment]
Having dug into this, FileSizeCache isn't persistent, which explains why it doesn't work across restarts.

At the moment I can't dig much further to see whether there's any reason not to make that another AssetCache subclass. There may be good reasons not to persist this information. And that's largely down to the fact that I'm somewhat over my head as this is my first look at anything serious with node.js anyway :)

**Comment by dimitrinicolas** [comment]
I'm sorry, I haven't been into 11ty image for a moment, and I never used remote images fetching. Good luck in your research! 😄

**Comment by zachleat** [comment]
Since it came up in the Eleventy Meetup today, here’s a quick config-based solution that won’t build images that haven’t changed (after the initial build):

```js
const eleventyImage = require("@11ty/eleventy-img");

module.exports = function(eleventyConfig) {
  let modifiedFiles = [];
  let imageCount = 0;

  eleventyConfig.on("beforeWatch", (files) => {
    modifiedFiles = files;
  });

  eleventyConfig.on("beforeBuild", () => {
    imageCount = 0;
  });

  eleventyConfig.on("afterBuild", () => {
    console.log( `Processed ${imageCount} image${imageCount !== 1 ? "s" : ""}.` );
  });

  eleventyConfig.addJavaScriptFunction("eleventyImage", function(src, options) {
    // During watch/serve, only generate images that have been modified.
    if(!modifiedFiles || modifiedFiles.length === 0 || modifiedFiles.indexOf(src) > -1) {
      imageCount++;
      return eleventyImage(src, options);
    }
  });
}
```

**Comment by zachleat** [comment]
Here’s a smaller version that doesn’t have the counter:

```js
const eleventyImage = require("@11ty/eleventy-img");

module.exports = function(eleventyConfig) {
  let modifiedFiles = [];

  eleventyConfig.on("beforeWatch", (files) => {
    modifiedFiles = files;
  });

  eleventyConfig.addJavaScriptFunction("eleventyImage", function(src, options) {
    // During watch/serve, only generate images that have been modified.
    if(!modifiedFiles || modifiedFiles.includes(src)) {
      return eleventyImage(src, options);
    }
  });
}
```

**Comment by brycewray** [comment]
Thanks very much, @zachleat — but guess I’ll have to wait until it’s incorporated in the regular `eleventy-img` examples (https://www.11ty.dev/docs/plugins/image/#use-this-in-your-templates) since I can’t seem to translate either of these to shortcode creation as opposed to `addJavaScriptFunction`. That’s my fault, not yours, of course! Much obliged for your answer today in the Eleventy Meetup as well as these code samples.

**Comment by zachleat** [comment]
Oh, I’ve made a mistake in my code, sorry about that! I’ll fix it

**Comment by zachleat** [comment]
So I went down the rabbit hole here, perhaps unnecessarily. Just to rewind a bit—we’re all aware of the existing In-Memory Cache feature right? https://www.11ty.dev/docs/plugins/image/#in-memory-cache-new-in-image-0.7.0

(this issue is specific to persisting the in-memory cache to the file system)

The approach documented here is unnecessary when `useCache: true` https://github.com/11ty/eleventy-img/issues/51#issuecomment-880938400

**Comment by zeroby0** [comment]
I've been disabling resizing and transcoding in development entirely. Image optimisation happens at Netlify during prod build.

Not the fix to this issue, but I hope it helps till the cache is fixed :D

```js
const imageShortcode = async(
    src,
    alt,
    widths = [300, 600, 900, 1200],
    formats = ['avif', 'webp', 'jpeg'],
    sizes = '(min-width: 640px) 90vw, (min-width: 768px) 80vw, 60vw'
) => {

    if (process.env.ELEVENTY_ENV == 'development') {
        widths = [null]
        formats = [null]
    }

    let metadata = await Image(src, {
        widths,
        formats,
        outputDir: '_site/img/',
    })

    let imageAttributes = {
        alt,
        sizes,
    }

    return Image.generateHTML(metadata, imageAttributes)
}
```

**Comment by marcamos** [comment]
Hi! Sorry, complete amateur chiming in here as I've tried interpreting the latest comments—and implementing the code provided in the most recent instance—and, _I think_, it's not working as desired … at least for me. No matter what I try, I can't get the cache to persist when I come back to my project a 2nd, 3rd, etc. time.

Each time I open the project and run (in my case) `npm run dev`, it churns through all of the images again and finally has the local environment ready to view about 100 seconds later, despite those images not changing in any way, shape, or form since the last time I opened and worked on the project.

…or, is this to be expected as eleventy-img is _not_ setup for this particular scenario?

…double-or, am I a dope and completely missing something here?

♥️

**Comment by zeroby0** [comment]
Try using this PR, @marcamos https://github.com/11ty/eleventy-img/pull/116

```bash
npm r @11ty/eleventy-img 
npm i zeroby0/eleventy-img#cache
```

And if you do rimraf on the output folder, make sure you exclude the image output folder.
Examples here:
- https://github.com/zeroby0/netlify-plugin-11ty/#i-rimraf-my-_site-on-every-build
- https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/pull/99

**Comment by brycewray** [comment]
@marcamos It works for only remote images, not local images — the latter of which is what I asked @zachleat about during an Eleventy Meetup session, which I think is part of why he entered the conversation here recently. Unfortunately, doesn’t appear that caching local images to streamline the dev process is in the cards for the plugin, at least for the time being. Perhaps there are programmatic reasons why; I’m not qualified to guess.

**Comment by tobystokes** [comment]
fwiw, I have local images caching, i.e. not rebuilt on initial run based on @dimitrinicolas' [previous answer](https://github.com/11ty/eleventy-img/issues/51#issuecomment-775186353)

If a nunjucks shortcode is of any use to you, see https://gist.github.com/tobystokes/b4b8bb743ec4c57317f6ef043093ff95

**Comment by zachleat** [comment]
@brycewray @marcamos https://github.com/11ty/eleventy-img/pull/116 @zeroby0 has a PR open to add this, pending review!

**Comment by zeroby0** [comment]
@zachleat Thanks :D ! Do you think there is someone I can request to review it?  For some reason I have received no feedback or suggestions on it. I'm new to the repos, I don't know how things work here

**Comment by zachleat** [comment]
@zeroby0 I added a few comments—it’s looking super solid!

**Comment by zachleat** [comment]
Shipping this with 1.0—thank you!
